root = "."
tmp_dir = "tmp"

[build]
cmd = "go run ./cmd/lighthouse/main.go"
bin = "tmp/app"
include_ext = ["go", "templ", "css", "html"]
exclude_dir = ["tmp", "vendor", ".cache"]
include_dir = ["ui", "cmd", "internal"]
delay = 500
stop_on_error = true