name: Checks

on:
  workflow_call: {}

jobs:
  check:
    runs-on: ${{ vars.RUNS_ON }}
    strategy:
      fail-fast: false
      matrix:
        command:
          - go/fumpt
          - go/vulnerability
          - go/lint
          - go/test
    steps:
      - uses: actions/checkout@v4

      - name: Compute toolchain tag
        id: tc
        shell: bash
        run: |
          GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
          echo "tag=${GO_VERSION}${{ vars.IMAGE_PATCH }}" >> $GITHUB_OUTPUT

      - name: Get Cache
        id: cache_get
        uses: ./.github/actions/cache-get
        with:
          toolchain_tag: ${{ steps.tc.outputs.tag }}

      - name: Run ${{ matrix.command }}
        uses: soltiHQ/actions/taskfile@main
        with:
          command: ${{ matrix.command }}

      - name: Put Cache
        uses: ./.github/actions/cache-put
        with:
          toolchain_tag: ${{ steps.tc.outputs.tag }}
